[client]
user = "Yakupov"
password = "1Qz2876"
api = "http://94.127.179.181:9081"

[rest]
host = ""
port = 3250

[mail]
host = "mail.nic.ru"
port = 587
user = "robot@davidoffclub.ru"
addressee = "robot"
password = "SwITERyCHEwConoT1"
subject = "OLAP report"
recipients = ["sergey@skoredin.pro"]

[daemon]
timeout = 3600
scheduler = "20 15 * * *"