[client]
    user="Yakupov"
    password="1Qz2876"
    api="http://94.127.179.181:9081"

[mail]
    host="mail.nic.ru"
    port=587
    user="robot@davidoffclub.ru"
    addressee="robot"
    password="SwITERyCHEwConoT1"
    subject="test"
    recipients=["s@skoredin.pro","sergey@skoredin.pro"]

[daemon]
    timout=3600
    scheduler="0 9 * * *"